<#
.SYNOPSIS
    Install Windows Explorer context menu integration for cold storage.

.DESCRIPTION
    This script adds a right-click context menu option to Windows Explorer
    that allows users to stage files/folders for cold storage archival.

    Requires Administrator privileges to modify the registry.

.PARAMETER ScriptPath
    Path where the cold storage scripts are installed.
    Defaults to C:\Scripts

.PARAMETER Uninstall
    Remove the context menu integration.

.EXAMPLE
    .\Install-ContextMenu.ps1

.EXAMPLE
    .\Install-ContextMenu.ps1 -ScriptPath "D:\MyScripts"

.EXAMPLE
    .\Install-ContextMenu.ps1 -Uninstall

.NOTES
    Author: Claude Code
    Requires: Administrator privileges
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$ScriptPath = "C:\Scripts",

    [Parameter()]
    [switch]$Uninstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

#region Helper Functions

function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Install-ContextMenuEntries {
    param([string]$ScriptPath)

    $moveScript = Join-Path $ScriptPath "Move-ToColdStorage.ps1"

    if (-not (Test-Path $moveScript)) {
        Write-Host "Warning: Move-ToColdStorage.ps1 not found at $moveScript" -ForegroundColor Yellow
        Write-Host "Make sure to copy the scripts to $ScriptPath before using the context menu." -ForegroundColor Yellow
    }

    # Command to execute - use PowerShell to run the script
    $command = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$moveScript`" `"%1`""

    # Registry paths for context menu
    $registryPaths = @(
        # For files
        @{
            Path = "HKCR:\*\shell\ColdStorageStaging"
            Command = "HKCR:\*\shell\ColdStorageStaging\command"
        },
        # For folders
        @{
            Path = "HKCR:\Directory\shell\ColdStorageStaging"
            Command = "HKCR:\Directory\shell\ColdStorageStaging\command"
        },
        # For folder background (right-click in empty space)
        @{
            Path = "HKCR:\Directory\Background\shell\ColdStorageStaging"
            Command = "HKCR:\Directory\Background\shell\ColdStorageStaging\command"
        }
    )

    # Create HKCR: PSDrive if it doesn't exist
    if (-not (Test-Path "HKCR:")) {
        New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT | Out-Null
    }

    foreach ($reg in $registryPaths) {
        Write-Host "Creating: $($reg.Path)"

        # Create the shell key
        if (-not (Test-Path $reg.Path)) {
            New-Item -Path $reg.Path -Force | Out-Null
        }

        # Set display name and icon
        Set-ItemProperty -Path $reg.Path -Name "(Default)" -Value "Move to Cold Storage Staging"
        Set-ItemProperty -Path $reg.Path -Name "Icon" -Value "shell32.dll,145"  # Archive icon

        # Create command subkey
        if (-not (Test-Path $reg.Command)) {
            New-Item -Path $reg.Command -Force | Out-Null
        }

        # Set command - handle the path specially for Background context
        if ($reg.Path -like "*Background*") {
            $bgCommand = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$moveScript`" `"%V`""
            Set-ItemProperty -Path $reg.Command -Name "(Default)" -Value $bgCommand
        } else {
            Set-ItemProperty -Path $reg.Command -Name "(Default)" -Value $command
        }
    }

    Write-Host ""
    Write-Host "Context menu entries installed successfully!" -ForegroundColor Green
}

function Uninstall-ContextMenuEntries {
    $registryPaths = @(
        "HKCR:\*\shell\ColdStorageStaging",
        "HKCR:\Directory\shell\ColdStorageStaging",
        "HKCR:\Directory\Background\shell\ColdStorageStaging"
    )

    # Create HKCR: PSDrive if it doesn't exist
    if (-not (Test-Path "HKCR:")) {
        New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT | Out-Null
    }

    foreach ($path in $registryPaths) {
        if (Test-Path $path) {
            Write-Host "Removing: $path"
            Remove-Item -Path $path -Recurse -Force
        }
    }

    Write-Host ""
    Write-Host "Context menu entries removed successfully!" -ForegroundColor Green
}

function Export-RegistryFile {
    <#
    .SYNOPSIS
        Export a .reg file for manual installation.
    #>
    param([string]$ScriptPath)

    $moveScript = Join-Path $ScriptPath "Move-ToColdStorage.ps1"
    # Escape backslashes for .reg file format
    $escapedPath = $moveScript.Replace('\', '\\')

    $regContent = @"
Windows Registry Editor Version 5.00

; Cold Storage Context Menu Integration
; Generated by Install-ContextMenu.ps1

; Context menu for files
[HKEY_CLASSES_ROOT\*\shell\ColdStorageStaging]
@="Move to Cold Storage Staging"
"Icon"="shell32.dll,145"

[HKEY_CLASSES_ROOT\*\shell\ColdStorageStaging\command]
@="powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"$escapedPath\" \"%1\""

; Context menu for folders
[HKEY_CLASSES_ROOT\Directory\shell\ColdStorageStaging]
@="Move to Cold Storage Staging"
"Icon"="shell32.dll,145"

[HKEY_CLASSES_ROOT\Directory\shell\ColdStorageStaging\command]
@="powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"$escapedPath\" \"%1\""

; Context menu for folder background
[HKEY_CLASSES_ROOT\Directory\Background\shell\ColdStorageStaging]
@="Move to Cold Storage Staging"
"Icon"="shell32.dll,145"

[HKEY_CLASSES_ROOT\Directory\Background\shell\ColdStorageStaging\command]
@="powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"$escapedPath\" \"%V\""
"@

    $regFile = Join-Path $ScriptPath "add-context-menu.reg"
    $regContent | Out-File -FilePath $regFile -Encoding ASCII

    Write-Host "Registry file created: $regFile" -ForegroundColor Green
    Write-Host ""
    Write-Host "To install manually:"
    Write-Host "  1. Right-click $regFile"
    Write-Host "  2. Select 'Merge'"
    Write-Host "  3. Confirm the UAC prompt"

    # Also create uninstall .reg file
    $uninstallContent = @"
Windows Registry Editor Version 5.00

; Cold Storage Context Menu Removal
; Generated by Install-ContextMenu.ps1

[-HKEY_CLASSES_ROOT\*\shell\ColdStorageStaging]
[-HKEY_CLASSES_ROOT\Directory\shell\ColdStorageStaging]
[-HKEY_CLASSES_ROOT\Directory\Background\shell\ColdStorageStaging]
"@

    $uninstallFile = Join-Path $ScriptPath "remove-context-menu.reg"
    $uninstallContent | Out-File -FilePath $uninstallFile -Encoding ASCII

    Write-Host ""
    Write-Host "Uninstall registry file created: $uninstallFile" -ForegroundColor Green
}

#endregion

#region Main Script

function Main {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "  Cold Storage Context Menu Setup      " -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""

    # Check if running on Windows (requires PowerShell Core 7+)
    if (-not $IsWindows) {
        Write-Host "This script is only for Windows." -ForegroundColor Yellow
        Write-Host "Generating .reg files for manual installation..."
        Export-RegistryFile -ScriptPath $ScriptPath
        return
    }

    # Check administrator privileges
    if (-not (Test-Administrator)) {
        Write-Host "Administrator privileges required." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Options:"
        Write-Host "  1. Run this script as Administrator"
        Write-Host "  2. Use the generated .reg files for manual installation"
        Write-Host ""

        # Generate .reg files as fallback
        Export-RegistryFile -ScriptPath $ScriptPath
        return
    }

    if ($Uninstall) {
        Write-Host "Removing context menu integration..."
        Uninstall-ContextMenuEntries
    } else {
        Write-Host "Installing context menu integration..."
        Write-Host "Script path: $ScriptPath"
        Write-Host ""
        Install-ContextMenuEntries -ScriptPath $ScriptPath

        # Also generate .reg files for reference
        Write-Host ""
        Write-Host "Generating .reg files for reference..."
        Export-RegistryFile -ScriptPath $ScriptPath
    }

    Write-Host ""
    Write-Host "Done!" -ForegroundColor Green
}

# Run main function
try {
    Main
    exit 0
} catch {
    Write-Host "ERROR: $_" -ForegroundColor Red
    exit 1
}

#endregion
